//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Database
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
   
    public partial class Student
    {
   
        public int StudentID { get; set; }
   
        public string StudentName { get; set; }
    }
}
